// Story genres - high-level categories
export const GENRES = [
  'Fantasy',
  'Sci-Fi',
  'Romance',
  'Horror',
  'Mystery',
  'Thriller',
  'Adventure',
  'Drama',
  'Comedy',
  'Action',
  'Historical',
  'Slice of Life',
  'Urban Fantasy',
  'Epic Fantasy',
  'LitRPG',
  'Gamelit',
  'Xianxia',
  'Wuxia',
  'Isekai',
  'Progression Fantasy',
]

// Story tags - specific content markers
export const TAGS = [
  'Strong Lead',
  'Female Lead',
  'Male Lead',
  'Non-Human Lead',
  'Multiple POV',
  'First Person',
  'Third Person',
  'Anti-Hero',
  'Villain Protagonist',
  'Magic',
  'Monsters',
  'Dungeons',
  'System',
  'Cultivation',
  'Reincarnation',
  'Time Travel',
  'Portal Fantasy',
  'Post-Apocalyptic',
  'Space Opera',
  'Cyberpunk',
  'Steampunk',
  'Military',
  'War',
  'Politics',
  'Kingdom Building',
  'Tower Climbing',
  'School Life',
  'Romance Subplot',
  'Harem',
  'Slow Romance',
  'No Romance',
  'Dark',
  'Grimdark',
  'Light-Hearted',
  'Comedy',
  'Tragedy',
  'Gore',
  'Profanity',
  'Sexual Content',
  'LGBTQ+',
  'Overpowered MC',
  'Weak to Strong',
  'Smart MC',
  'Strategy',
  'Survival',
  'Crafting',
  'Pets/Companions',
  'Dragons',
  'Vampires',
  'Werewolves',
  'Zombies',
  'Elves',
  'Dwarves',
  'Gods',
  'Demons',
]

// Community Picks
export const COMMUNITY_PICK_MIN_XP = 250; // "regular" tier
export const COMMUNITY_PICK_MAX_VOTES_PER_MONTH = 3;
export const COMMUNITY_PICK_MIN_WORDS = 10000;
